### ISSUE TITLE
Resolve wrong IP address from hostname

### ISSUE THREAD

**Issue by Aspire1Inspire2** [developerfromjokela/motioneye-client#11]
![Screenshot_20200112-192258](https://user-images.githubusercontent.com/12798470/72228037-12ba5780-3571-11ea-8835-06da45d55d02.jpg)

My motioneye is behind reverse proxyed https
However, the IP address is not resolved correctly from name server.

My actual IP address begins with 76
Please see attached screenshot.

**Comment by developerfromjokela** [comment]
Is it working when you're visiting it in a browser?

**Comment by Aspire1Inspire2** [comment]
Yes, it is working using browser.

**Comment by developerfromjokela** [comment]
Can you try again adding the device with that hostname?

**Comment by developerfromjokela** [comment]
Can you provide me the hostname?

**Comment by Aspire1Inspire2** [comment]
Hi, I send it to you via email.

**Comment by developerfromjokela** [comment]
Hello, 
I saw the issue when I was looking to your hostname. 

Your url was xxxxx.xx/something, and the bug caused the url to be xxxxx.xx/something:8765, the port number is in wrong place. It should be xxxxx.xx:8765/something.

I'll fix it soon. 
Thanks for reporting :smile:

**Comment by Aspire1Inspire2** [comment]
Actually, it is setup like this:
http://10.0.0.2:8765

Or:
https://my.webserver.hostname/motioneye/
Or:
https://my.webserver.hostname:443/motioneye/

The port for my hostname is using the default 443 port for SSL. Since I used the reverse proxy, the localhost port 8765 on the server is not accessible from my hostname. 

Cheers!

**Comment by developerfromjokela** [comment]
Now the bug is fixed.

**Comment by developerfromjokela** [comment]
Update will be released within this week
