### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by szimszon** [developerfromjokela/motioneye-client#13]
Hi,

I wonder if you could help me.

I created a demo CA for myself and imported it to my Android phone. I sign all internal certificate with this CA in the same way.
This process works with a new official HomeAssistant android client.

If I may ask you to make this great app work with certificates signed with a custom CA which in turn is already imported into the Android phone. 

Thank you!

I'm using a stock Android 9 from Samsung.

**Comment by developerfromjokela** [comment]
Hello,

Thanks for reporting the issue!

It requires me to make a setting to import the certificate to my app, because for security issues Android doesn't import them automatically.

**Comment by developerfromjokela** [comment]
In the latest commit, it will accept already imported user certificates. I haven't tested yet, but I will do it later.

**Comment by developerfromjokela** [comment]
Tested, it's working

**Comment by szimszon** [comment]
Works for me. Thank you!
