### ISSUE TITLE
Stuck in setup

### ISSUE THREAD

**Issue by stilltldr** [developerfromjokela/motioneye-client#14]
Hi,

in the configuration dialogue I'm stuck in the step "select local WiFi network"

Android Version 10
OxygenOS 10.3.2 on a OnePlus 6

![Screenshot_20200531-174810](https://user-images.githubusercontent.com/35105355/83356604-71893d80-a367-11ea-9e4d-71ef098796e3.jpg)

The button cannot be pressed, only going back is possible.

Questions welcome

**Comment by developerfromjokela** [comment]
Hello,


Where did you download from? 
There's an outdated version on F-Droid that I'm unable to update for some reasons. You can always find the latest version from Google Play, it should have the patch which fixed that issue earlier.
Here's the link to Play store: [https://play.google.com/store/apps/details?id=com.developerfromjokela.motioneyeclient](https://play.google.com/store/apps/details?id=com.developerfromjokela.motioneyeclient)

**Comment by developerfromjokela** [comment]
Hello,

With our upcoming release, Wi-Fi selecting won't be required anymore.
