### ISSUE TITLE
[Issue] App on F-Droid is outdated

### ISSUE THREAD

**Issue by ovz93br43v7** [developerfromjokela/motioneye-client#18]
Hello,

I wanted to know whether this app is still maintained?

Thanks in advance!

**Comment by developerfromjokela** [comment]
Hello!
Yes, it is still maintained by me.

**Comment by ovz93br43v7** [comment]
Good to know :)
My question was because on F-Droid is just an very old version of your app (15.10.2019) but on Github I see you have a newer release published.
Can you somehow push the newest release to F-Droid?

On a additional question: I can't find any privacy policy, do you collect any data from the users of your app?

**Comment by developerfromjokela** [comment]
Hello!

Yes, the app on F-Droid is using old version, and I haven't been able to
update it for some reason. I'll look into it later this week.

About the privacy policy, no the app does not collect any data as its
source code indicates, Google Play version is just compiled APK from latest
version, so no data collected.

**Comment by ovz93br43v7** [comment]
One additional question, the apk files on github are named: [...]-signed-[...].apk
Does this "signed" mean I can verify the apk with your public gpg key?

**Comment by developerfromjokela** [comment]
Those APKs are signed with my keystore in Android Studio. I could publish
my public certificate, so yes, you could verify, you just need the public
certificate for it.

**Comment by developerfromjokela** [comment]
Take a look: [https://android.stackexchange.com/questions/9312/how-can-i-verify-the-authenticity-of-an-apk-file-i-downloaded](https://android.stackexchange.com/questions/9312/how-can-i-verify-the-authenticity-of-an-apk-file-i-downloaded)

**Comment by ovz93br43v7** [comment]
Thanks.
I created in parallel a ticket at f-droid: https://gitlab.com/fdroid/fdroiddata/-/issues/2242

**Comment by developerfromjokela** [comment]
@ovz93br43v7 F-Droid doesn't upload apps themselves, developers upload themselves, so in some kind of way "blaming" F-Droid isn't quite correct. The issue has been on my side, so I'll try my best to make it work, so we can get latest version on F-Droid.

**Comment by ovz93br43v7** [comment]
ok sorry I have closed it.
