### ISSUE TITLE
Support for hass.io motion eye (docker) addon

### ISSUE THREAD

**Issue by rradar** [developerfromjokela/motioneye-client#2]
I tried any possible _ip/hostname/port_ combination but couldn't get my motion eye instance hooked up to the app. The url motion eye is exposed and I'm trying to access with the app is `hostname:8123/a0d7b954_motioneye`

Here is the description of the addon: https://github.com/hassio-addons/addon-motioneye

**Comment by developerfromjokela** [comment]
Hello,

Can you try to paste that link into the IP address textbox, which you provided without filling the port number?

**Comment by rradar** [comment]
Hey @developerfromjokela 

thank's for the quick reply. I tried that too without success. By now I think I'm trying to connect to the wrong url. It rather needs something to like this  `hostname:8123/api/hassio_ingress/BKbzyoK49UeYKePUinXf_Clk69IUlEziWX026MOliPQ/`.

The thing is that their is **one more authentication** from home assistant to cope with... :thinking:

**Comment by developerfromjokela** [comment]
Hello, 

I think we can't solve this without running home assistant myself. Let's return tomorrow, as I'm willing to spend this day to install it. 😀

**Comment by rradar** [comment]
https://www.home-assistant.io/docs/authentication/ is the link to the docs for the auth system.

**Comment by developerfromjokela** [comment]
Ok, thanks, I'll look at it tomorrow.

Thank you for opening an issue. I appreciate it. 😄

la 19. lokak. 2019 klo 23.27 rradar <notifications@github.com> kirjoitti:

**Comment by developerfromjokela** [comment]
I've set up my own home assistant and motioneye inside, I'm trying to solve your problem.

**Comment by developerfromjokela** [comment]
I've found out, that home assistant requires its own authentication before accessing motionEye. 
I'll integrate it into motionEye app soon. Stay tuned!

@developerfromjokela

**Comment by ptc** [comment]
You can expose motioneye to the outside if you set the port number in the add-on settings. I can access from outside then by entering my-homeassistant-host:8082 and have to login. But this unfortunately doesn't work with your app.

**Comment by developerfromjokela** [comment]
What's wrong with My app, can you give More details so I can possibly fix The issue?

**Comment by developerfromjokela** [comment]
@rradar Have you tried to expose the local port as @ptc recommended?

**Comment by developerfromjokela** [comment]
> You can expose motioneye to the outside if you set the port number in the add-on settings. I can access from outside then by entering my-homeassistant-host:8082 and have to login. But this unfortunately doesn't work with your app.

There was an issue that i.e. proxying via Apache didn't work because it has different Server header compared to MotionEye. I've removed that check and it should work with any server whatsoever. @ptc can you try again?

**Comment by rradar** [comment]
Just to confirm that this works now when setting a dedicated port for it in the hassio motioneye addon :tada: 

It does not yet work with the f-droid release because[ it's quite old](https://github.com/developerfromjokela/motioneye-client/issues/19) :grimacing:
