### ISSUE TITLE
Can't pass Select WiFi Network

### ISSUE THREAD

**Issue by JHenzi** [developerfromjokela/motioneye-client#3]
I'm excited to get this working, right before you published it I was looking on f-droid for a client. 

I went to add my first device on the Pixel 3 and I can't get past the Select Local WiFi Network page. Unsure if I should be seeing a list there, on or off WiFi didn't seem to have a difference.

**Comment by JHenzi** [comment]
Checked the app permissions, and none are requested to Android, so not sure if this could be the issue.

**Comment by developerfromjokela** [comment]
Which Android version are you using? 9 or 10?

**Comment by developerfromjokela** [comment]
On Android 10, there is an new privacy change, none of apps that aren't system, can't read configured WiFi networks. I'll try to solve this problem.

**Comment by developerfromjokela** [comment]
Problem is in location permissions. I'll push a new update as soon as possible.

**Comment by developerfromjokela** [comment]
Next time you should grant location permission to MotionEye Client, and it should show Wifi networks.

**Comment by JHenzi** [comment]
Thanks - sorry I wasn't faster to respond earlier. Had to get a microcenter trip in. And correct, Android 10. I read this permission is intertwined now.

**Comment by developerfromjokela** [comment]
I've fixed that issue. It will take a day or two to get it on f-droid. I
recommend to downloading that update through Google Play, as it's currently
available there, or you can wait it to be published on F-Droid, by your
choice of course 😀.

**Comment by developerfromjokela** [comment]
Reopen this issue, if it still exists.

**Comment by JHenzi** [comment]
Awesome! I'll keep my eyes peeled for the update. Play says it's not yet there for me.

**Comment by developerfromjokela** [comment]
Update is already live, check again, maybe it just autoupdated?

**Comment by jeff-h** [comment]
I also experienced the same issue. Turns out I was using v1.0.0-alp9 which is prior to this fix. I found your app on [f-droid](https://f-droid.org/en/packages/com.developerfromjokela.motioneyeclient/) and unfortunately the version distributed from there is still 1.0.0-alp9.

**Comment by developerfromjokela** [comment]
Yes, I'm having a trouble putting the latest version to the github.

**Comment by developerfromjokela** [comment]
Last time I tried it ended up to be a complete mess.

**Comment by developerfromjokela** [comment]
On some Xiaomi Devices problem still exists in Android 10.

**Comment by developerfromjokela** [comment]
I've added an button to skip Wi-Fi selection
