### ISSUE TITLE
Can't add device by hostname 

### ISSUE THREAD

**Issue by agilob** [developerfromjokela/motioneye-client#5]
Normally I access my local devices by their hostname, like `rpi0.local` and I don't care aobut their dynamic IP address, but the app doesn't let me add device by hostname, it expects only IP address.

**Comment by developerfromjokela** [comment]
Hello,
I've ran into this issue myself, so it will be fixed in next update. 😀

Regards,
@developerfromjokela

**Comment by developerfromjokela** [comment]
Hello,

It's complete now, and will be included in the next update. 
:smile:
