### ISSUE TITLE
App quit when use https in DDNS

### ISSUE THREAD

**Issue by Aspire1Inspire2** [developerfromjokela/motioneye-client#6]
I have setup reverse proxy to use motioneye behind Apache2's https.
When I am trying to add the "https://my.web.address/motioneye/" string to the DDNS address field, the app will error out and quit.

**Comment by developerfromjokela** [comment]
Hello,

I tried myself entering that, and it crashes. 
I'll try my best to fix that as soon as possible.

**Comment by developerfromjokela** [comment]
Small update: Got it working. There's little work left to do, then I'll publish the new update. :wink:

**Comment by Aspire1Inspire2** [comment]
Thank you! 😁

**Comment by 3bT8b1stYeA2s** [comment]
Not sure if this helps but it seems to be the colon character ":" that is causing the app to crash. I experienced this after adding a "device" then trying to modify it just as Aspire1Inspire2 mentioned adding 'the "https://my.web.address/motioneye/" string to the DDNS address field"
I tried adding just the colon and it crashes.

FWIW I'm using nginx as reverse proxy.

**Comment by developerfromjokela** [comment]
Ok, so now it's working. Open this issue again if it occurs again. :smile:

**Comment by rezzalex** [comment]
Hello @developerfromjokela, I just switched to Nginx and I have the error message "unauthorized" when trying to access from WAN, then, if I refresh the screen :  

 `https://mydomainname:443/motioneye/picture/1/current?_=xxxxx&username=xxx&signature=xxxxxxxxxxxxxxx
`

In my motioneye android client config, I have the full "`https://mydomainname /motioneye`" url in DDNSHOSTAME and 443 in DDNS port.

Here is my NGINX.conf :  

	location /motioneye/
	{
      rewrite ^/motioneye/?(.*) /$1 break;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Scheme $scheme;
      proxy_pass http://192.168.xx.xx:xxxx/; #local ipno to motioneye
      proxy_read_timeout  90;
	}
	
	location /video/ {
    proxy_pass http://192.168.x.xx/video/;
    proxy_read_timeout 86400;
	}
	
	location /image/ {
    proxy_pass https://192.168.xx.xx/image/;
    proxy_read_timeout 86400;
}
