### ISSUE TITLE
Cannot add device

### ISSUE THREAD

**Issue by faezzi** [developerfromjokela/motioneye-client#7]
When trying to add my camera to the app I get an error:

java.lang.IllegalStatException: Expected a boolean but was NUMBER at line 1 column 658 path $.cameras[0].still_images

Below there are three green ticks for "Checking Local Connection" , "DDNS Connection" and "Trying to login". After that there is a red exclamation mark "Get Information about motionEye"

Checking in the browser shows that everything is working fine. I can login and see my camera. I installed version 1.0.0-alp9 from f-droid.

Edit:

DId not mention but maybe it matters: I use motioneyeOS on a raspberry.

**Comment by faezzi** [comment]
I think I 'fixed' it myself... My motioneyeos was still a 2017xxxx version. Did an upgrade and I can add the device.

**Comment by developerfromjokela** [comment]
Great!
