### ISSUE TITLE
Stuck during add wizard

### ISSUE THREAD

**Issue by ouafnico** [developerfromjokela/motioneye-client#8]
Hi

When trying to add a device, I'm stuck on this page.
Can't click anywhere, using wifi or not is not changing anything.
![Screenshot_20191130-222646](https://user-images.githubusercontent.com/807350/69906231-a4567700-13c0-11ea-8849-9bc246385c50.png)

**Comment by developerfromjokela** [comment]
Hello,

Have you downloaded the app from F-Droid?

 If that's your case, try downloading from Google Play. F-Droid one is
outdated.

If it isn't, we can discuss more about this problem tomorrow 😉.

**Comment by ouafnico** [comment]
Hum yes I installed it from fdroid. 
On play store it's running well !

Thanks !
