### ISSUE TITLE
light_off and light_on action buttons unresponsive.

### ISSUE THREAD

**Issue by Clewsy** [developerfromjokela/motioneye-client#9]
I created a couple of custom actions (light_on_1 and light_off_1) that work fine through the webui but are unresponsive through the android client.

I also note the symbols used differ - light bulbs in the webui but lightning bolts in your android client.

PTZ actions created for an additional camera work fine through both interfaces.

I love your work!

**Comment by developerfromjokela** [comment]
Hello, 

Can you clarify more what do you mean by "unresponsive"?

Thanks!

**Comment by Clewsy** [comment]
Sure thing, I just mean when I press the lightning bolts, nothing happens.

As mentioned, in the webui, pressing the light bulb action buttons has the expected response.

**Comment by developerfromjokela** [comment]
Hello, I did some tweaking, hope it helps. Feel free to open this issue again, if this bug still exists.
:smiley:

**Comment by Clewsy** [comment]
Great!  I'm F-Droid only so I'll have to wait until it reaches that repo.  Thanks again. :)

**Comment by developerfromjokela** [comment]
Ok, the update is live in google play, not yet in F-Droid. So you'll have to wait for some time. 😉
